version: '3'
services:
  rabbit.mq:
    image: rabbitmq:3.10.20-management-alpine
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - .env
    networks:
      - spu011_network
    ports:
      - "5672:5672"
      - "15672:15672"

  front_vue:
    build: ./front_vue
    volumes:
      - ./front_vue:/usr/src/app
    command: sh -c " npm install && npm start "
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - spu011_network

  back_java:
    build: ./back_java
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - spu011_network
    depends_on:
      - db.mysql.main
    expose:
      - "8080"
    environment:
      - NAME=back_java

  db.mysql.main:
    image: 'mysql/mysql-server:latest'
    ports:
      - '3366:3306'
    env_file:
      - .env
    volumes:
      - './volumes/db/mysql/main:/var/lib/mysql'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - spu011_network

networks:
  spu011_network:
    driver: bridge